arm-software/embedded/scripts/build.bat, arm-software/embedded/scripts/build.sh, arm-software/embedded/scripts/test.bat, arm-software/embedded/scripts/test.sh
This introduces a set of bash and batch scripts to run builds and tests
for the Arm Toolchain For Embedded. These scripts can be used for
building the toolchain from source, and will be used by CI in the
future.
=> Add scripts to run builds and tests for ATfE

arm-software/embedded/arm-multilib/json/variants/armv6m_soft_nofp_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv6m_soft_nofp_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7a_hard_vfpv3_d16_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7a_hard_vfpv3_d16_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7a_soft_nofp_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7a_soft_nofp_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7a_soft_vfpv3_d16_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7a_soft_vfpv3_d16_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7m_hard_fpv4_sp_d16_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7m_hard_fpv4_sp_d16_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7m_soft_fpv4_sp_d16_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7m_soft_fpv4_sp_d16_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7m_soft_nofp_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7m_soft_nofp_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7r_hard_vfpv3_d16_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7r_hard_vfpv3_d16_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7r_hard_vfpv3xd_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7r_hard_vfpv3xd_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7r_soft_nofp_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7r_soft_nofp_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7r_soft_vfpv3xd_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv7r_soft_vfpv3xd_unaligned.json
Each variant has a name property which should match the filename, however there are a number of variants where differences have crept in. In particular, the "unaligned" suffix appears missing in many cases.
=> Ensure variant names are unique and match filenames

arm-software/ci/automerge.py
The automerge script failed just now (for a benign transient reason), and printed this:
ERROR: Failed to run command: "[ ' g i t ' ,   ' - C ' ,   ' / h o m e / r u n n e r / w o r k / a r m - t o o l c h a i n / a r m - t o o l c h a i n ' ,   ' p u s h ' ,   ' o r i g i n ' ,   ' a r m - s o f t w a r e ' ]"
because `error.cmd` was a list of strings, and the error message tried to format it using `" ".join(str(error.cmd))`, which first converted the list into a single string the same way `__repr__` would have done it (displaying the list in Python syntax with strings quoted), and then applied `" ".join` to the resulting string, which caused it to be treated as a list of characters, and each pair of characters separated with a space.
The sensible way to format a shell command in …
=> automerge: make error-message formatting less amusing.

arm-software/linux/build.sh, arm-software/linux/mkmoduledirs.sh.var
This is a proof of concept script which generates a directory tree with modulefiles. It may be used later when the RPM and DEB post-install shell scripts are being implemented.
Currently it can be used as such:
In the ATfL tarball (as created by build.sh) a new directory called `arm` is being created containing the `mkmodulesdir.sh` script. This script is being amended by `build.sh` in order to adjust the ATfL version info. After unpacking the tarball, an user can execute this script, it will create three directories in the current directory:
```
moduledeps
modulefiles
moduleglobals
```
These contain all the files needed to load ATfL as a module.
Assuming this script has been executed in the `atfl/arm` directory in the user's `$HOME`, ATfL can be loaded as such:
```
$ …
```
=> [ATfL] A script which generates modulefiles directory tree that could be pointed at with MODULEPATH

arm-software/embedded/newlib-samples/src/baremetal-semihosting-newlib/hello.c, arm-software/embedded/newlib-samples/src/cpp-baremetal-semihosting-newlib/hello.cpp, arm-software/embedded/samples/src/baremetal-semihosting-aarch64/hello.c, arm-software/embedded/samples/src/baremetal-semihosting/hello.c, arm-software/embedded/samples/src/baremetal-uart/hello.c, arm-software/embedded/samples/src/cpp-baremetal-semihosting-cfi/hello.cpp, arm-software/embedded/samples/src/cpp-baremetal-semihosting-exceptions/hello-exn.cpp, arm-software/embedded/samples/src/cpp-baremetal-semihosting-exceptions/hello.cpp, arm-software/embedded/samples/src/cpp-baremetal-semihosting-prof/hello.cpp, arm-software/embedded/samples/src/cpp-baremetal-semihosting-prof/proflib.c, arm-software/embedded/samples/src/cpp-baremetal-semihosting-ubsan/hello.cpp, arm-software/embedded/samples/src/cpp-baremetal-semihosting-ubsan/libubsan.cpp, arm-software/embedded/samples/src/cpp-baremetal-semihosting/hello.cpp
Add missing Arm copyright notices to C and C++ files under the samples folders.
=> Add Arm copyright notices to samples

arm-software/embedded/CMakeLists.txt
Remove unused LLVM_TOOLCHAIN_DISTRIBUTION_COMPONENTS_ALL and add the llvm-toolchain-mingw target directly to LLVM_TOOLCHAIN_DISTRIBUTION_COMPONENTS to fix mingw build.
=> Remove unused variable to fix mingw build

arm-software/linux/build.sh-HOWTO.md
This is to add support for compressed binaries. If this library is not
present, such support is silently disabled. We already have it enabled
in Ubuntu builds.
=> [ATfL] According to rpmfind, libzstd-static is available for RHEL9, so we should use it

arm-software/embedded/arm-runtimes/CMakeLists.txt
Like the other directories, the stamp and build directories for llvmlibc-support project need to use a unique identifier for each variant build, otherwise multiple versions of the same project may attempt to use them. The download and temp directories are already set properly.
=> Use variant id in stamp and binary dirs for llvmlibc-support

arm-software/embedded/arm-runtimes/CMakeLists.txt
The libcxx tests attempt to detect the presence of a -std=c++NN flag, however this does not use the correct multilib flags for the library variants built once they have been installed to the clang runtimes folder. As a result, the tests will likely report an issue with the compiler when only a single library variant is built, as multilib will not be able to find a match.
To fix this, this patch ensures the sysroot is in the compile flags used in the libcxx tests, so that the tests are run using the known library location instead of using multilib..
=> Ensure sysroot is set when running libcxx tests

arm-software/embedded/scripts/build_llvmlibc_overlay.sh, arm-software/embedded/scripts/build_newlib_overlay.sh
This introduces two new scripts for building ovelay library packages for
the Arm Toolchain for Embedded, one for the newlib overlay and one for
the llvmlibc overlay.
The scripts follow the same approach as the existing `build.sh` script,
but using different build directories and providing the corresponding
CMake options for each overlay package.
=> [ATfE] Add scripts to build newlib and llvmlibc overlay packages

arm-software/embedded/arm-runtimes/test-support/run_fvp.py
Corstone prints out some informational text to stdout, but this text conflicts with expectations from tests about the contents of stdout.
This patch filters out this text to send to stdout only what matters.
=> Filter Corstone's stdout

arm-software/embedded/arm-multilib/json/variants/armebv6m_soft_nofp.json, arm-software/embedded/arm-multilib/json/variants/armebv6m_soft_nofp_exn_rtti.json
Some libcxx tests are failing on this variant, despite whether any of the failures are exclusive to this variant is unknown.
For now the libcxx tests will remain disabled while we focus on having C library tests passing for new variants we add.
=> Disable libcxx tests on armebv6m_soft_nofp variants

arm-software/embedded/llvmlibc-samples/src/llvmlibc/baremetal-semihosting/Makefile
The sample program calls two libm functions (lround and atanf) to turn a floating-point number into decimal digits. But libm.a is built as a separate library from libc.a, so linking the sample program fails because the compile command doesn't use the -lm option. Easily fixed.
=> Fix llvmlibc sample, by adding -lm to the link command.

arm-software/embedded/fvp/get_fvps.sh
The get_fvps.sh script currently only downloads and installs the Linux64 versions of the FVPs, which does not necessarily match the host. AArch64 versions of the downloads are all available, so this patch adds a simple check to download the appropriate ones.
This also updates the version of the Corstone-310 FVP to 11.27, and modifies the script to infer the package names from the URL to reduce duplication when modifying links.
=> Add support for downloading AArch64 versions of FVPs

arm-software/linux/build.sh, arm-software/linux/build.sh-HOWTO.md
This patch fixes two problems:
1. Following line caused inconsistency between the variable described in help (LOG_DIR) and the one actually read (LOGS_DIR):
LOG_DIR=${LOGS_DIR:-"${BASE_DIR}/logs"}
2. All the CI scripts including the ones which execute this script are setting and using the LOGS_DIR variable.
=> [ATfL] Fix LOG_DIR vs. LOGS_DIR inconsistency

.github/workflows/automerge.yml, .github/workflows/sync_from_upstream.yml
Currently workflows that exist under `.github/workflows` are executed
not only on arm/arm-toolchain, but on all forks of this repo, including
personal forks used for development and submitting PRs.
To prevent that from happening, this change adds a condition to the
existing workflows, checking if the current repo is arm/arm-toolchain
before running.
=> Ensure workflows only run on arm/arm-toolchain and not on forks

arm-software/embedded/arm-runtimes/meson-cross-build.txt.in
Currently, the wrapper command for running picolibc tests in ATfE
includes a direct call to the `picolibc-test-wrapper.py` script, relying
on the script's shebang line to invoke the python interpreter. This is a
problem for invoking tests on Windows platofrms, as the naming of the
Python 3 executable is not consistent with the one used on Unix - i.e.
python vs python3.
To fix this problem, this change adds the path for the python executable
to that call. The path used is the one discovered by CMake as part of
the `find_package(Python3 ...)` command.
Cherry-picked from commit 9b283bc (#70)
=> [ATfE] Use python executable path for picolibc tests

arm-software/embedded/arm-runtimes/test-support/run_fvp.py, arm-software/embedded/fvp/config/m-pacbti.cfg
The new version of Corstone-310 FVP model has a few differences compared to v11.24 which require changes:
* The `ID_ISAR5.PACBTI` parameter has been deprecated and removed.
* The install now includes its own copy of pythonlib and fmtplib, the paths to which need to be set as environment variables before starting the model. `PYTHONHOME` should be set to `<install>/python`, and `LD_LIBRARY_PATH` to `<install>/fmtplib:<install>/python/lib`.
* The boilerplate message printed to stdout has a different date, and the Info message on stop is no longer present. The regex has been updated to still match.
=> Update scripts and config for Corstone-310 v11.27

arm-software/linux/build.sh
OS name can be used to specify the target OS, along with the targeted distribution name and version, e.g., `RHEL10`.
=> [ATfL] Add ability to specify OS name, and update help text

arm-software/embedded/patches/picolibc/0001-Enable-libcxx-builds.patch, arm-software/embedded/patches/picolibc/0002-Define-picocrt_machines-for-AArch32-builds-as-well-a.patch, arm-software/embedded/patches/picolibc/0003-Add-support-for-strict-align-no-unaligned-access-in-.patch
Commit 0dad9b1 (Add support for target-specific section names in picolibc.ld) in the picolibc repository prevents
0001-Enable-libcxx-builds.patch from being applied cleanly. Only the context around our patches has changed, so a simple rebase is enough to make them apply cleanly again.
=> Rebase picolibc patches

arm-software/embedded/arm-multilib/multilib.yaml.in, arm-software/embedded/test/multilib/armv7a.test
These variants were missing some logic in multilib.yaml: some of the flag matching rules existed only for little endian. Thus they had to be copied for big endian as well.
Besides the changes to multilib.yaml, tests have been added to properly test the library selection of the variants.
=> Add logic to multilib.yaml to handle cases of armebv7a_soft_nofp and armebv7a_hard_vfpv3_d16 variants

arm-software/embedded/scripts/build.sh
If FVPs have been installed using the `get_fvps.sh` script, then this patch allows them to be used in the `build.sh` script by setting the `FVP_INSTALL_DIR` environment variable to the install location.
=> [ATfE] Enable FVP testing in build script if available

.github/workflows/automerge.yml
This updates the "Automerge" workflow to use the same App Access Token
used by the "Sync from Upstream LLVM" workflow. This is necessary to
allow the aotumerge script to bypass the branch protection rules of the
repo, once PR approvals are required for merges.
=> Update Automerge workflow to use App Access Token

arm-software/embedded/arm-runtimes/test-support/run_fvp.py
The `run_fvp.py` script currently only supports running the x86_64 versions of the models, due to the paths containing a directory that only exists in the x86_64 package. This patch adjusts the paths depending on the platform, which allows the script to run both x86_64 and AArch64 versions.
=> [ATfE] Adjust expected FVP file locations based on platform

arm-software/embedded/patches/llvm-project-perf/0001-Pipelines-Additional-unrolling-in-LTO.patch, arm-software/embedded/patches/llvm-project-perf/0002-ARM-CodeGen-Prefer-MEMCPY-LDM-STM-inlining-for-v7-m.patch
The `Additional unrolling in LTO` patch has been rebased against an upstream change, while `Prefer MEMCPY LDM/STM inlining for v7-m` has had the original commit message restored in order to provide context for the change.
The filenames now also match the subject of the commit message, as they have been regenerated using git format-patch.
=> [ATfE] Update downstream performance patches

arm-software/linux/build.sh
The compilers.yaml file generated by build.sh can be copied into $HOME/.spack/linux/compilers.yaml to integrate the fresh build of ATfL with Spack without doing any additional installation steps.
=> [ATfL] Prepare compilers.yaml to help integrating the fresh ATfL build with Spack

clang/lib/CodeGen/CGBuiltin.cpp, clang/test/CodeGen/AArch64/sincos.c, clang/test/CodeGen/math-libcalls.c
This will allow vectorizing these calls (after a few more patches). This should not change the codegen for targets that enable the use of AA during the codegen (in `TargetSubtargetInfo::useAA()`). This includes targets such as AArch64. This notably does not include x86 but can be worked around by passing `-mllvm -combiner-global-alias-analysis=true` to clang.
---
Downstream issue: #87
=> (release 20.x non-upstream patch) [clang] Lower non-builtin sincos[f|l] calls to llvm.sincos.* when -fno-math-errno is set

arm-software/embedded/fvp/config/v8a-aarch32.cfg, arm-software/embedded/fvp/config/v8a-aarch64.cfg, arm-software/embedded/fvp/config/v8r-aarch32.cfg, arm-software/embedded/fvp/config/v8r-aarch64.cfg
The FVP models include an implementation of a sound device, however when running a large number of tests concurrently this can cause errors with the sound driver.
Since we do not need audio output for our tests, this patch disables the audio device.
=> [ATfE] Disable audio device in FVP tests

arm-software/embedded/arm-multilib/json/variants/armebv6m_soft_nofp.json, arm-software/embedded/arm-multilib/json/variants/armebv6m_soft_nofp_exn_rtti.json
Some libcxx tests are failing on this variant, despite whether any of the failures are exclusive to this variant is unknown.
For now the libcxx tests will remain disabled while we focus on having C library tests passing for new variants we add.
(cherry picked from https://github.com/arm/arm-toolchain/pull/66)
=> Disable libcxx tests on armebv6m_soft_nofp variants (#66)

arm-software/embedded/arm-multilib/json/multilib.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_be_soft_nofp.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_be_soft_nofp_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_soft_nofp.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_soft_nofp_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_soft_nofp_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_soft_nofp_unaligned.json, arm-software/embedded/arm-multilib/multilib.yaml.in, arm-software/embedded/test/multilib/aarch64.test, arm-software/embedded/test/multilib/armv7a.test
Add AArch64 R-profile soft nofp variants (LE and BE) - (cherry picked from https://github.com/arm/arm-toolchain/pull/102)
Add logic to multilib.yaml to handle cases of armebv7a_soft_nofp and armebv7a_hard_vfpv3_d16 variants- (cherry picked from https://github.com/arm/arm-toolchain/pull/99)
Remove -mno-unaligned-access flag from AArch32 big endian variants -(cherry picked from https://github.com/arm/arm-toolchain/pull/115)
=> Cherry-pick: Integrating Changes from PR #99, #102 and #115

arm-software/embedded/arm-multilib/json/multilib.json, arm-software/embedded/llvmlibc-samples/src/llvmlibc/baremetal-semihosting/Makefile
Fix llvmlibc sample, by adding -lm to the link command - Cherry pick from https://github.com/arm/arm-toolchain/pull/69
Do not build aarch64r soft_nofp variants with newlib/llvmlibc - Cherry pick from https://github.com/arm/arm-toolchain/pull/110
=> Cherry-pick: Integrating Changes from PR #69 and #110

arm-software/embedded/patches/llvm-project/0001-libc-tests-with-picolibc-xfail-one-remaining-test.patch, arm-software/embedded/patches/llvm-project/0002-libc-tests-with-picolibc-disable-large-tests.patch, arm-software/embedded/patches/llvm-project/0003-Disable-failing-compiler-rt-test.patch, arm-software/embedded/patches/llvm-project/0004-libc-tests-with-picolibc-XFAIL-uses-of-atomics.patch, arm-software/embedded/patches/llvm-project/0005-libc-tests-with-picolibc-mark-two-more-large-tests.patch, arm-software/embedded/patches/llvm-project/0006-Define-_LIBCPP_HAS_C8RTOMB_MBRTOC8.patch, arm-software/embedded/patches/llvm-project/0007-libcxx-Remove-xfails-due-to-picolibc-s-support-for-c.patch, arm-software/embedded/patches/llvm-project/0008-PATCH-Revert-order-of-libraries-and-update-tests.patch, arm-software/embedded/patches/llvm-project/0009-compiler-rt-Fix-tests-of-__aeabi_-idivmod-uidivmod-u.patch, arm-software/embedded/patches/llvm-project/0010-compiler-rt-Add-support-for-big-endian-for-Arm-s-__n.patch, arm-software/embedded/patches/llvm-project/0011-libcxx-Work-around-picolibc-argv-handling-in-tests.-.patch
We need to incorporate the following upstreamed patches into the 20.x branch. So applying these as patch files.
[compiler-rt] Add support for big endian for Arm's __negdf2vfp - (cherry picked from https://github.com/llvm/llvm-project/pull/127096)
[compiler-rt] Fix tests of _aeabi(idivmod|uidivmod|uldivmod) to support big endian - (cherry picked from https://github.com/llvm/llvm-project/pull/126277)
[libcxx] Work around picolibc argv handling in tests - (cherry picked from https://github.com/llvm/llvm-project/pull/127662)
=> Update llvm-project patch files to integrate changes from #126277, #127096 and #127662

arm-software/embedded/arm-runtimes/CMakeLists.txt, arm-software/embedded/arm-runtimes/meson-cross-build.txt.in
Picolibc contains one C++ test, which is failing for me when building with meson 1.4.1, but not 1.3.1. In the failing case, the test is being compiled and linked using clang++ from my PATH, not the freshly built one. With meson 1.3.1, the same compiler is being used for both C and C++, so this test works correctly. I don't see anything in the meson changelog which could cause this, but setting the c++ compiler in the same way we do for C makes this test work for both meson versions.
=> Fix picolibc C++ test with meson 1.4

arm-software/linux/build.sh
At the shared_lib_build stage we do not need ZSTD as the main goal of this stage is to provide shared runtime libraries, while ZSTD is being used at compile time. Sadly, there is no way (yet) to eliminate remaining attempts to build other things at this stage, and some of this stuff is linked against libzstd. Unfortunately, on some Linux distributions, those static variants of libraries that we are using to build ATfL were not built with -fPIC, resulting in linker failures. The only way to prevent this is to override one of the COMMON_CMAKE_FLAGS and disable the use of ZSTD at this stage.
=> [ATfL] Do not use libzstd.a when building shared runtime libs

arm-software/linux/build.sh, arm-software/linux/build.sh-HOWTO.md
Amazon Linux uses different target triple than other distributions. An attempt to accomodate it in Clang's frontend driver has been rejected already [1], so the only way to handle it is to set the default target triple explicitly when building LLVM. This will affect the name of the runtimes library which LLVM creates.
[1] https://github.com/llvm/llvm-project/pull/109263
=> [ATfL] Introduce the ability to set the default target triple

arm-software/linux/build.sh, arm-software/linux/build.sh-HOWTO.md
Amazon Linux uses different target triple than other distributions. An attempt to accomodate it in Clang's frontend driver has been rejected already [1], so the only way to handle it is to set the default target triple explicitly when building LLVM. This will affect the name of the runtimes library which LLVM creates.
[1] https://github.com/llvm/llvm-project/pull/109263
=> [ATfL] Introduce the ability to set the default target triple (#131)

arm-software/linux/build.sh-HOWTO.md
Two things were changed:
- We do not require `figlet` anymore, its installation is optional
- There are packages which are missing in default installations of some of the RPM-based systems
=> [ATfL] Update the list of dependencies

arm-software/embedded/scripts/test.sh, arm-software/embedded/scripts/test_libcxx.sh
The `check-all` target runs upstream tests, which by default do not generate an XML results file. This can be done through a lit option.
The `--ignore-fail` option should also be set for the libcxx test script, in the same way as the main test script.
=> [ATfE] Store check-all results and continue libcxx tests on failure

arm-software/linux/build.sh-HOWTO.md
=> [ATfL] Add missing description of the OS_NAME variable into our HOWTO document

arm-software/embedded/patches/llvm-project/0012-libc-Do-not-guard-inclusion-of-wchar.h-with-_LIBCPP_.patch
This change is required for the newlib-nano library overlay
implementation to work correctly, as it provides the definition
`mbstate_t` despite not providing wide-character support.
=> [ATfE] Cherry-pick libcxx change in wchar inclusion guarding into 20.x

arm-software/linux/build.sh
The compiler we build will still be targeting AArch64 only, but with some luck this may work on some other platforms too.
=> [ATfL] Make it more adaptive to the build platform

arm-software/embedded/fvp/config/v8a-aarch32.cfg, arm-software/embedded/fvp/config/v8a-aarch64.cfg, arm-software/embedded/fvp/config/v8r-aarch32.cfg, arm-software/embedded/fvp/config/v8r-aarch64.cfg, arm-software/embedded/scripts/test.sh, arm-software/embedded/scripts/test_libcxx.sh
Cherry pick of three changes to the release branch with no modification:
- Disable audio device in FVP tests (#113) (77958d290d811601f41d0ee9f581980e156ab63e)
- Add additional test targets to test script (#116) (9c425650b0f36b1bd00cf93701e3445a840c2067)
- Store check-all results and continue libcxx tests on failure (#151) (3428e354dd3724bb015deb3bc18e31e7e0396d08)
=> [ATfE] Cherry-pick PRs #113, #116 and #151

arm-software/embedded/CMakeLists.txt, arm-software/embedded/cmake/generate_toolchain_id.cmake
In order to uniquely identify ATfE builds, this patch populates the new Arm Toolchain ID with an auto-generated tag.
This tag contains both the product code (E for Embedded), as well as a unique identifier for the build. In a Jenkins environment, this will be based on the build URL and build number.
=> [ATfE] Set Arm Toolchain ID

arm-software/embedded/versions.json
This commit hash (be1b69f5f5910d216c16f9fca927c1bdb4d38a51) corresponds to a commit from February 10, 2025. However, the fix for the 'X' specifier issue was
introduced in a later commit on February 12, 2025. Therefore, the current picolibc version in the ATFE 20.x branch does not include this fix. To resolve the current libcxx test failure locale_time_put_members.put2.pass.cpp, update the versions.json file in the ATFE 20.x branch to reference a picolibc commit that includes the necessary fix.
=> Resolve time formatting issue in ATFE 20.x by updating Picolibc version.

.github/workflows/automerge.yml
This temporarily disables Automerge workflow runs for the 20.x release
branch. As the 20.1.0 release approaches upstream, this is necessary to
ensure the commit used for the Arm Toolchain release is consistent
with the one used upstream.
While the Automerge is disabled for the branch, any incoming changes
from upstream will be reviewed and manually merged into the downstream
`release/arm-software/20.x` branch.
The workflow will be re-enabled for the branch once the release is done.
=> Temporarily disable automerge for 20.x release branch

arm-software/embedded/arm-runtimes/CMakeLists.txt, arm-software/embedded/arm-runtimes/check-picolibc.cmake.in
The meson test command will return the number of test failures. If any test fails, this will be non-zero, which the CMake script will interpret as the command failing. The test command is immediately followed by a second command to process the results, so this will not get executed on a failure. Since the processing sets the names in the results file to make them variant specific, this makes it very unclear from the XML results which tests failed, and causes other tests not to run.
To get around this, this patch wraps the meson test command in a new CMake script which can handle the return code. Since the other lit-based tests already use the `--ignore-fail` option to control whether or not to continue on a test failure, this script will also honour the option in the `LIT_OPTS` …
=> [ATfE] Handle meson test return code in picolibc tests

arm-software/embedded/arm-multilib/json/variants/armebv7m_hard_fpv4_sp_d16.json, arm-software/embedded/arm-multilib/json/variants/armebv7m_hard_fpv4_sp_d16_exn_rtti.json
Some libcxx tests are failing on this variant, despite whether any of the failures are exclusive to this variant is unknown.
For now the libcxx tests will remain disabled while we focus on having C library tests passing for new variants we add.
=> Disable libcxx tests on armebv7m_hard_fpv4_sp_d16 variants.

arm-software/embedded/arm-multilib/json/variants/armebv7m_hard_fpv4_sp_d16.json, arm-software/embedded/arm-multilib/json/variants/armebv7m_hard_fpv4_sp_d16_exn_rtti.json
Some libcxx tests are failing on this variant, despite whether any of the failures are exclusive to this variant is unknown.
For now the libcxx tests will remain disabled while we focus on having C library tests passing for new variants we add.
(cherry picked from commit b4a8b67d75ce61b5b996ca2a98e3fce813a4a4d0)
=> Disable libcxx tests on armebv7m_hard_fpv4_sp_d16 variants. (#172)

arm-software/embedded/arm-runtimes/CMakeLists.txt, arm-software/embedded/arm-runtimes/check-picolibc.cmake.in
The `LIT_OPTS` environment variable should be evaluated at runtime, not during configuration. The `@ONLY` option can be used to limit replacement to only the variables that need replacing during configuration.
Additionally, compiling the tests has been added as a dependancy of building the library so that it can be done in parallel.
=> [ATfE] Restrict variable replacement in check-picolibc script

arm-software/embedded/arm-runtimes/CMakeLists.txt, arm-software/embedded/arm-runtimes/check-picolibc.cmake.in
Both these changes are required to run a full set of tests from the test script without the build stopping on the first picolibc failure.
=> [ATfE] Cherry-pick PRs #162 and #175 to 20.x release branch

arm-software/ci/automerge.py
This patch introduces an additional check at the start of the automerge
script to ensure that it only runs on a clean git worktree. This check
prevents issues where local changes might be included unintentionally as
part of merge commits.
=> Ensure automerge only runs on a clean git worktree

.github/workflows/automerge.yml
This updates the Automerge Workflow to use a `git pull --unshallow`
command instead of `git fetch --unshallow` to obtain the history of the
target branch. Using `git pull` ensures the worktree contents will also
be correctly up-to-date if any new changes are added to the remote
between the 'Checkout' step and the 'Fetch Branches' step.
=> Use pull to update target branch in Automerge Workflow

arm-software/embedded/CMakeLists.txt, arm-software/embedded/cmake/generate_toolchain_id.cmake, arm-software/shared/cmake/generate_toolchain_id.cmake
Cherry-picks of two PRs to enable setting Arm Toolchain ID on the 20.x release branch:
- Set Arm Toolchain ID (#127) (e0066d133eeb6053f5b8937689a9f6c5c0663f90)
- Move Toolchain ID script to shared location (#170) (17138e2dc6add72a701f6ed4f7b373855f9c871c)
There is also one additional commit only for the release branch, which removes the `pre` suffix from the ID since these are no longer pre-release builds.
=> [ATfE] Set Arm Toolchain ID in ATfE on 20.x release branch

arm-software/linux/mkmoduledirs.sh.var
Removed moduleglobals as unused global functions removed
The simple is-lmod function is moved to the main module file
moduledeps left as it is due to autocompletion still uses it
=> [ATfL] Simplify the modulefiles structure

arm-software/embedded/CMakeLists.txt
Setting the suffix to nothing will correctly generate the toolchain ID, but leads to an incorrectly formatted package name. Instead, the suffix should not be set at all.
=> [ATfE] Remove pre-release package suffix

arm-software/linux/build.sh
=> [ATfL] If BUILD_NUMBER is available, we should use it

arm-software/embedded/ATfE-SBOM-llvmlibc-overlay.spdx.json, arm-software/embedded/ATfE-SBOM-newlib-overlay.spdx.json, arm-software/embedded/ATfE-SBOM.spdx.json, arm-software/embedded/CMakeLists.txt, arm-software/embedded/scripts/SBOM_Files/generate_ATfE-SBOM-llvmlibc-overlay.py, arm-software/embedded/scripts/SBOM_Files/generate_ATfE-SBOM-newlib-overlay.py, arm-software/embedded/scripts/SBOM_Files/generate_ATfE-SBOM.py
Add SBOM JSON files for ATfE, llvmlibc overlay and newlib overlay; and Python scripts which generate these SBOM JSON files.
This is cherry-pick from arm-software branch commit: e5cde593ba2c951c0df5be388524f7b518efc4b2
=> Add SBOM JSON files for ATfE, llvmlibc overlay and newlib overlay (#183)

arm-software/linux/build.sh, arm-software/linux/mkmoduledirs.sh.var
Fixes the initial lmod support and extends bash autocompletion to the arm?lang* commands when the mkmodulesdirs.sh script is run.
=> [ATfL] Support bash autocompletion and lmod

arm-software/embedded/cmake/generate_version_txt.cmake
Fix newlib-nano VERSION.TXT git commit by using base_library variable consistently.
=> Fix newlib-nano VERSION.TXT git commit

arm-software/embedded/arm-runtimes/test-support/run_fvp.py
When running a test using an FVP, in order to propagate an exit code from the program a `:semihosting-features` file is created in the working directory. Since tests are usually run in parallel across multiple processes using the same shared directory, one process can attempt to read the file at the same time another is replacing and rewriting it.
This patch replaces the file with an atomic operation instead of opening a new file in its place.
=> [ATfE] Don't overwrite semihosting-features file in FVP tests

arm-software/embedded/arm-runtimes/test-support/run_fvp.py
The NamedTemporaryFile used to create the `:semihosting-features` file for FVP testing will automatically attempt to delete itself when closed. Since this file needs to persist in order to replace any existing copy of the file, the auto deletion must be disabled.
The `os.rename` operation has also been changed to `os.replace` since renaming to an existing file will throw an error on some operating systems such as Windows.
=> [ATfE] Don't delete temporary semihosting-features file

arm-software/embedded/patches/llvm-project/0015-llvm-ar-Fix-darwin-related-tests-XFAIL-annotation-13.patch
This cherry-picks the upstream change from https://github.com/llvm/llvm-project/pull/130144,
which landed on the `main` branch, into our 20.x release. The change is
included as a patch file for llvm.
=> Cherry-pick fix for darwin-related tests' XFAIL annotations

clang/test/CodeGen/RISCV/attr-riscv-rvv-vector-bits-less-8-call.c, clang/test/CodeGen/RISCV/attr-riscv-rvv-vector-bits-less-8-cast.c, clang/test/CodeGen/RISCV/attr-rvv-vector-bits-cast.c, clang/test/CodeGen/attr-arm-sve-vector-bits-cast.c, llvm/include/llvm/IR/Attributes.h, llvm/include/llvm/IR/DerivedTypes.h, llvm/lib/IR/AttributeImpl.h, llvm/lib/IR/Attributes.cpp, llvm/lib/Transforms/Scalar/SROA.cpp, llvm/test/Transforms/SROA/scalable-vectors-with-known-vscale.ll
It's a cherry-pick from the sve-vls-sroa branch of Paul Walker's LLVM fork.
Ongoing upstream attempt:
https://github.com/llvm/llvm-project/pull/130973
Downstream issue: #218
For function whose vscale_range is limited to a single value we can size scalable vectors. This aids SROA by allowing scalable vector load and store operations to be considered for replacement whereby bitcasts through memory can be replaced by vector insert or extract operations.
=> [Downstream change][LLVM][SROA] Teach SROA how to "bitcast" between fixed and scalable vectors

arm-software/embedded/patches/picolibc/0001-Enable-libcxx-builds.patch, arm-software/embedded/patches/picolibc/0002-Define-picocrt_machines-for-AArch32-builds-as-well-a.patch, arm-software/embedded/patches/picolibc/0003-Add-support-for-strict-align-no-unaligned-access-in-.patch
Recent upstream changes to picolibc mean the downstream patches no longer apply due to the context around them changing:
* The retargetable locking condition was removed.
* Various `_HAVE_` symbols were changed to `__HAVE_`.
* `PREFER_SIZE_OVER_SPEED` changed to `__PREFER_SIZE_OVER_SPEED`.
The downstream modifications themselves remain unchanged.
=> [ATfE] Rebase picolibc patches

arm-software/embedded/samples/src/cpp-baremetal-semihosting-exceptions/make.bat
The make.bat was missing -nostartfiles for the clang++.exe invocations. This prevented the samples from exiting cleanly.
The other cpp-* samples have -nostartfiles in their make.bat.
=> Fix cpp-baremetal-semihosting-exceptions on Windows (#224)

arm-software/embedded/samples/src/baremetal-semihosting-aarch64/Makefile
Make a temporary fix to avoid a couple of problems with the startup code on more recent qemu versions, such as the recent 9.2.2 release.
The first problem is that the thunk generated for the branch from _start to _cstart loads the destination address from a literal. As this thunk executes before the memory is set up we get an abort on the read. Fix this by forcing the linker to use a position independent thunk that is execute-only.
The second problem is that the picolibc startup code assumes that qemu-system-aarch64 will start in EL1. This is not always the case. When --kernel is an ELF file qemu will start in EL3, when --kernel is not ELF then qemu will start in either EL2 (if implemented) or EL1, with EL2 preferred. When starting up in EL2 this means that the startup code writing to EL1 …
=> Make baremetal-semihosting-aarch64 sample work on recent qemu

arm-software/embedded/samples/src/baremetal-semihosting-aarch64/Makefile
Make a temporary fix to avoid a couple of problems with the startup code on more recent qemu versions, such as the recent 9.2.2 release.
The first problem is that the thunk generated for the branch from _start to _cstart loads the destination address from a literal. As this thunk executes before the memory is set up we get an abort on the read. Fix this by forcing the linker to use a position independent thunk that is execute-only.
The second problem is that the picolibc startup code assumes that qemu-system-aarch64 will start in EL1. This is not always the case. When --kernel is an ELF file qemu will start in EL3, when --kernel is not ELF then qemu will start in either EL2 (if implemented) or EL1, with EL2 preferred. When starting up in EL2 this means that the startup code writing to EL1 …
=> Make baremetal-semihosting-aarch64 sample work on recent qemu (#227)

arm-software/embedded/patches/picolibc/0004-AArch32-crt0-don-t-write-to-VBAR-on-Armv7-R-systems.patch
This is logically a cherry-pick of
https://github.com/picolibc/picolibc/pull/973
aka picolibc commit b399940a9e590032b6dff9f325215c41ac6dbde2 by turning it into a patch to be applied against the version of picolibc checked out by our build scripts.
=> [picolibc patch] AArch32 crt0: don't write to VBAR on Armv7-R

arm-software/embedded/arm-multilib/multilib.yaml.in, arm-software/embedded/test/multilib/armv8a.test
This mapping is necessary to make the multilib variant selection work for Armv8-A big endian, since the library variants supposed to be used in this case are chosen on the presence of the multilib flag corresponding to Armv7-A.
Besides this change, this commit introduces more testing to cover more cases of this mapping.
=> [ATfE] Add multilib.yaml mapping form Armv8-A big endian to Armv7-A big endian

arm-software/embedded/samples/src/baremetal-semihosting-aarch64/make.bat
This applies the change https://github.com/arm/arm-toolchain/pull/227 Makefile to the Windows make.bat. The rest of the commit message is the same as that PR.
Make a temporary fix to avoid a couple of problems with the startup code on more recent qemu versions, such as the recent 9.2.2 release.
The first problem is that the thunk generated for the branch from _start to _cstart loads the destination address from a literal. As this thunk executes before the memory is set up we get an abort on the read. Fix this by forcing the linker to use a position independent thunk that is execute-only.
The second problem is that the picolibc startup code assumes that qemu-system-aarch64 will start in EL1. This is not always the case. When --kernel is an ELF file qemu will start in EL3, when --kernel is …
=> Update baremetal-semihosting-aarch64 sample make.bat for qemu

arm-software/embedded/samples/src/baremetal-semihosting-aarch64/make.bat
This applies the change https://github.com/arm/arm-toolchain/pull/227 Makefile to the Windows make.bat. The rest of the commit message is the same as that PR.
Make a temporary fix to avoid a couple of problems with the startup code on more recent qemu versions, such as the recent 9.2.2 release.
The first problem is that the thunk generated for the branch from _start to _cstart loads the destination address from a literal. As this thunk executes before the memory is set up we get an abort on the read. Fix this by forcing the linker to use a position independent thunk that is execute-only.
The second problem is that the picolibc startup code assumes that qemu-system-aarch64 will start in EL1. This is not always the case. When --kernel is an ELF file qemu will start in EL3, when --kernel is …
=> Update baremetal-semihosting-aarch64 sample make.bat for qemu (#232)

arm-software/embedded/llvmlibc-samples/src/llvmlibc/baremetal-semihosting/make.bat
This adapts the existing make.bat files from the picolibc samples to the llvmlibc sample so that it can run on Windows.
=> Add make.bat for the llvmlibc sample

arm-software/embedded/llvmlibc-samples/src/llvmlibc/baremetal-semihosting/make.bat
This adapts the existing make.bat files from the picolibc samples to the llvmlibc sample so that it can run on Windows.
=> Add make.bat for the llvmlibc sample (#235)

clang/lib/Driver/ToolChains/CommonArgs.cpp, clang/test/Driver/fveclib.c, flang/test/Driver/fveclib.f90
Downstream issue: #242
Although combining -fveclib=ArmPL with -nostdlib is a rare situation, it should still be supported correctly and should effect in avoidance of linking against libm.
=> [Downstream change][clang][driver] Fix -fveclib=ArmPL issue: with -nostdlib do not link against libm

arm-software/embedded/CMakeLists.txt
Add CFI ignore file for ATfE. This fixes an issue observed with https://github.com/arm/arm-toolchain/commit/1ce251795b2d1bc31ff7c80989b5b188b334a2bd 
There are at least 3 ways by which cfi-ignore file can be invoked:
1. With the binary installer, by executing the program. For example: `clang --target=aarch64-none-elf -march=armv8-a -c test.c -flto -fsanitize=cfi -fvisibility=hidden`
2. With the binary installer, by executing the "cpp-baremetal-semihosting-cfi" example code in "samples" directory, without  "-fno-sanitize-ignorelist" in MakeFile
3. By compiling the source code and using the compiled binary to execute the program. For example: `./build/llvm/bin/clang --target=aarch64-none-elf -march=armv8-a -c test.c -flto -fsanitize=cfi -fvisibility=hidden`
Previous patch version did not …
=> Add CFI ignore file for ATfE.

arm-software/linux/build.sh
It turned out that libomp.a that we are shipping is useless.
It should not support OMPT as it tries to dlopen() libarcher.so
We are already building libomp.so with OMPT support enabled along with libarcher.so in the previous stage.
Fully operational libomp.a is needed by Allinea Smoke Tests.
With OMPT disabled, -ldl is not needed for OpenMP tests to pass, so the config file hack could be removed from build.sh.
=> [ATfL] OMPT support should not be built at that stage

arm-software/linux/build.sh
In my previous commit I've misread the reason why those two lines were introduced. Now we cannot build for RHEL8 and this patch restores those two lines.
=> [ATfL] Restore obligatory linking with -ldl. Apparently this is needed for RHEL8

arm-software/embedded/fvp/get_fvps.sh
The SYS_TICKFREQ semihosting call was failing on the previous FVP model. The latest FVP models for A and R now include a fix for this. This commit updates the FVP model to incorporate that fix.
=> [ATFE] Update FVP model to fix SYS_TICKFREQ semihosting issue

.github/workflows/atfe_nightly_build_and_test.yml, arm-software/embedded/scripts/install_dependencies.sh, arm-software/embedded/versions.json
Add nightly build and test workflow for ATfE
-  Initial support for Linux Ubuntu 22.04
-  Run all build scripts in parallel
-  Add install dependencies script
-  Update source for Newlib. Use GitHub mirror
=> Add nightly build and test workflow for ATfE

.github/workflows/atfe_nightly_build_and_test.yml, arm-software/embedded/scripts/install_dependencies.sh
- The missing package is causing an error when running build.sh
- Ensure the workflow only runs on the arm-toolchain repository
=> Install Qemu on GH actions hosts

clang/lib/Format/TokenAnnotator.cpp, clang/unittests/Format/FormatTest.cpp
Commit 8fc8a84e23471fe56214e68706addc712b5a2949 was accidentally removed in 9ca958ed24170ed7cdec84eb8f9530ce33b0d861 by the automerge script. This patch reapplies the changes to prevent a divergence from upstream.
=> Reapply missing commit

arm-software/linux/build.sh
Apparently, `make install` doesnt't do that
=> [ATfL] Copy top-level LLVM's LICENSE.TXT into our tarball

arm-software/embedded/arm-multilib/json/multilib.json, arm-software/embedded/arm-multilib/json/variants/armv8.1m.main_hard_fp_nomve_pacret_bti.json, arm-software/embedded/arm-multilib/json/variants/armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/armv8.1m.main_hard_fpdp_nomve_pacret_bti.json, arm-software/embedded/arm-multilib/json/variants/armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/armv8.1m.main_hard_nofp_mve.json, arm-software/embedded/arm-multilib/json/variants/armv8.1m.main_hard_nofp_mve_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/armv8.1m.main_hard_nofp_mve_pacret_bti.json, arm-software/embedded/arm-multilib/json/variants/armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/armv8.1m.main_soft_nofp_nomve_pacret_bti.json, arm-software/embedded/arm-multilib/json/variants/armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti.json, arm-software/embedded/test/multilib/armv8.1m.main.test
Two non-PACBTI variants needed a strictly aligned counterpart:
- armv8.1m.main_hard_nofp_mve
- armv8.1m.main_hard_nofp_mve_exn_rtti
because no suitable Armv7-M variant exists for these two as a fallback option. The combination of hard FP ABI and no FPU is not covered by our Armv7-M variants.
On the PACBTI side, all the existing variants needed their strictly aligned counterparts. This is because it's not safe to fallback to Armv7-M variants in this case, as these are not built for PACBTI.
This patch introduces new strictly aligned variants for Armv8.1-M Main. Two of them are for non-PACBTI + hard FP ABI + no FPU, while the rest is for all the PACBTI variants.
=> [ATfE] Add required strictly aligned variants for Armv8.1-M Main

.github/workflows/automerge.yml
This adds the workflow permissions required for creating Pull Requests
to the Automerge workflow. This is required as the automerge script
needs to create new Pull Requests for merge conflicts that must be
resolved manually.
=> [Automerge] Add workflow permissions for creating PRs

README.md, arm-software/embedded/README.md, arm-software/linux/README.md
Add Quick Links section (including ways to provide feedback) to the main README. 
Add feedback and contribution sections at the end of Linux toolchain README.
=> Add feedback sections to the docs

.github/workflows/automerge.yml
This updates the Automerge workflow to use a GitHub App token when
running the automerge.py script, instead of the regular GH_TOKEN. This
should allow the automerge scripts to create PRs in the
arm/arm-toolchain project when a merge conflict is encountered, as
workflows by default aren't allowed to do so.
=> [Automerge] Use App token when executing automerge script

.github/workflows/atfe_nightly_build_and_test.yml
- Meson is installed in ~/.local/bin
- We need to add the directory to the env PATH so that GitHub actions can use Meson
=> Add .local/bin to PATH

.github/workflows/atfe_nightly_build_and_test.yml
- The overlay build packages were not found with the previous wildcard pattern
- Remove unused path for test results
=> Fix build path for overlay builds

arm-software/embedded/CMakeLists.txt, arm-software/embedded/scripts/build.sh
If a system name for the package other than the CMake default is required, this can now be set through the `PACKAGE_SYSTEM_NAME` option. If unset, the default remains the CMake system name.
Additionally, the `build.sh` script has been modified so that additional CMake arguments can be passed down to CMake during configuration. `EXTRA_CMAKE_ARGS` can now be read as an environment variable, which will be appended to the arguments in the script.
=> [ATfE] Allow for a user specified system name when packaging

arm-software/embedded/arm-multilib/json/multilib.json
After https://github.com/llvm/llvm-project/pull/137592 is merged and the patch is collected downstream, these variants for LLVM-libc can be reenabled.
=> [ATfE] Re-enable LLVM-libc for nofp variants

arm-software/embedded/CMakeLists.txt
The package tests rely on CMake to extract the package, however the command used only supports tar and zip archives. Until an alternative solution is found to test the dmg archive produced on macOS, the package tests can instead be disabled to prevent a failure.
The `test.sh` script will still attempt to build the `check-package-llvm-toolchain` target, so a dummy target is created to avoid an unrecognized target error.
=> [ATfE] Disable package tests on macOS

arm-software/embedded/arm-multilib/json/multilib.json
https://github.com/arm/arm-toolchain/pull/314 should have only enabled aarch64 nofp variants for LLVM-libc builds. However it also enabled the variants for newlib builds, which were disabled since newlib is similarly unable to build those variants (see https://github.com/arm/arm-toolchain/pull/60#issuecomment-2648640369). While there is now a fix for the LLVM-libc build, there is yet no fix for newlib so they need to remain disabled for that selection.
This patch sets the variants to only build for picolibc and llvmlibc, but not newlib.
=> [ATfE] Re-disable aarch64 nofp variants for newlib

.github/workflows/automerge.yml
Now that the releases of version 20.1.0 of ATfE and ATfE are complete,
this patch re-enables the runs of the Automerge workflow targeting the
`release/arm-software/20.x` branch to ensure the code is up to date with
upstream LLVM.
=> Re-enable automerge for the 20.x release branch

.github/workflows/atfe_nightly_build_and_test.yml
Extend the nightly build-and-test workflow to run on both arm64 and x86_64 platforms. This change adds support for GitHub-hosted large runners targeting Linux x86_64, allowing us to validate toolchain builds across architectures.
This is part of an evaluation of GitHub’s large runners for Linux workloads.
=> Test large runners for Linux x86_64

arm-software/embedded/CMakeLists.txt, arm-software/embedded/patches/llvm-project/0018-Re-land-Analysis-Ensure-use-of-strict-fp-exceptions-.patch
This PR addresses two test failures after building ATfE 20.x on macOS:
- The `LLVM.Transforms/InstCombine.known-bits.ll` test fails due to an issue with constant folding. This was fixed in 67783eb166664cb0be9da01d1dc83178615a0575 which did not make it on to the release branch. The commit has instead been implemented as a patch applied at build time, together with other fixes that did not make the branch date.
- Attempting to run the package tests causes an error when CMake attempts to unpack the archive. The extractor currently only supports `tar` and `zip` archives, and so these tests should be disabled when other formats like `dmg` are used. This was done in commit 17e376e6f6bca3903b192aaf4b20a8ff6386dd84, which has been cherry-picked here.
=> [ATfE] Cherry-pick two patches to address test failures

arm-software/linux/build.sh
After the upstream commit [1] we could not build the product anymore.
Several things had to change:
- path to libc++ includes must be forcibly provided to the runtimes
- flang-rt must be explicitly listed for building
- we must explicitly ensure both static and shared build of flang-rt
- the `-DLLVM_ENABLE_LIBCXX=ON` flag has been removed to silence the compiler warnings
[1] https://github.com/llvm/llvm-project/commit/77581e27514db084da59738c4d26ed7e70a31736
=> [ATfL] build.sh modifications to accommodate the upstream changes

arm-software/embedded/arm-runtimes/test-support/run_fvp.py
Since the run_fvp.py script is imported into other scripts, the machine name check can be carried out on machines where FVP testing is not supported and disabled.
This patch moves the check inside the run function, so that it the machine name only needs to be matched when FVP tests are actually being executed.
(cherry picked from commit de90c62e12ee40165ce43453962c4a0f4b364d66)
=> [ATfE] Cherry pick updated FVP uname check to 20.x branch

arm-software/embedded/CMakeLists.txt, arm-software/embedded/scripts/extract_dmg.sh
The package test implementation curretly relies on using the CMake `tar`
command to unpack the toolchain for testing. As this CMake command is
not able to handle .dmg image files, the package test was disabled
temporarily on MacOS platforms.
This change implements an alternative way to unpack the toolchain .dmg
file for testing on MacOS. It introduces a new `extract_dmg.sh` script
that makes use of the `hdiutil` program to extract the contents
correctly. With the fix in place, this change also re-enables the
package tests on MacOS platforms.
=> [ATfE] Fix and re-enable package test on MacOS

arm-software/embedded/CMakeLists.txt, arm-software/shared/elf2bin/CMakeLists.txt
Adding it directly via `add_subdirectory` meant that it was built, but not installed as part of the overall toolchain package, because I hadn't manually included a cmake `install` command.
I'd expected that `add_llvm_tool` would set up installation automatically. But in fact it only does that if the tool is on the list in `LLVM_TOOLCHAIN_TOOLS`. Worse, if the installation targets aren't set up by the time the main LLVM cmake setup finishes running, then adding the tool to `LLVM_DISTRIBUTION_COMPONENTS` causes another error, because the end of the LLVM cmake setup tries to add dependencies to all those targets. So calling `add_subdirectory` after LLVM installation finishes is simply too late. You need to arrange that elf2bin's `CMakeLists.txt` is invoked _during_ LLVM configuration. …
=> Add elf2bin to the build via LLVM_EXTERNAL_PROJECTS

.github/workflows/atfe_nightly_build_and_test.yml, arm-software/embedded/scripts/build.ps1, arm-software/embedded/scripts/install_dependencies.ps1
- Qemu is a requirement to run Windows tests. Therefore, not needed for now
- Disable qemu testing
=> Remove tests for Windows 

arm-software/embedded/arm-runtimes/CMakeLists.txt
PR #60, which introduced it, set the build flags `-g -Oz` for newlib-nano (both libc and libcxx), and `-g -O2` for full newlib libcxx. `-g` was probably left over from development: in our production builds it's taking up a great deal of space, making the newlib-nano overlay archive more like ¾Gb than ¼Gb.
I've reverted the entire flags change for full newlib libcxx, putting it back to how it was before that PR. For newlib-nano, I've removed the `-g`, but kept `-Oz`, on the basis that optimizing for small size still seems sensible if someone's deliberately selecting the smallest version of newlib.
=> Remove -g flags from newlib variant builds

.github/workflows/check_downstream_changes.yml, arm-software/ci/check_downstream_changes.py
In order to follow the project's downstream patch policy (see CONTRIBUTING.md), modifications to the LLVM codebase (all files outside the arm-software sub-directory, with a few exceptions) need to have a issue opened in GitHub in order to track the changes, with the pull request linking to that issue.
This patch implements a Python script and a GitHub workflow to run the script whenever a pull request is opened or modified. The script takes a pull request number, and uses the GitHub command-line interface to get information about which files are changed, and whether the body text of the pull request contains the required linkage. To determine which files need tracking, the file changes are compared against the automerge ignore list, which already contains the rules for which files are …
=> Add automated check for downstream changes

arm-software/embedded/arm-multilib/json/variants/aarch64a.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_be.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_be_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_be_soft_nofp.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_be_soft_nofp_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_soft_nofp.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_soft_nofp_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_unaligned.json, arm-software/embedded/arm-multilib/json/variants/aarch64r.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_be.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_be_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_be_soft_nofp.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_be_soft_nofp_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_soft_nofp.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_soft_nofp_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_soft_nofp_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_soft_nofp_unaligned.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_unaligned.json
After recent bug fixes, the AArch64 compiler-rt tests are passing, therefore we are able to enable them all.
=> [ATfE] Enable aarch64 compiler-rt tests

arm-software/embedded/Omax.cfg, arm-software/embedded/OmaxLTO.cfg
Enabling this improves performance on a couple of embedded benchmarks.
=> [ATFE] Add -enable-loop-versioning-licm to Omax.cfg and OmaxLTO.cfg

arm-software/linux/build.sh
This commit removes disablement of generating the flang docs (man pages). It was disabled as it had been failing. We had to wait until a fix for generating flang manpages has landed upstream. See https://github.com/llvm/llvm-project/pull/141882
=> [ATfL] build.sh modification to generate flang/armflang manpages

.github/workflows/atfe_address_sanitizer_build_and_test.yml, arm-software/embedded/scripts/build_atfe_address_sanitizer.sh, arm-software/embedded/scripts/test_atfe_sanitizer.sh
Enable address sanitizer in Github Action for ATfE. Job executes only once a week, on 6pm on Sunday. It executes limited tests on the compiled binaries and results are NOT uploaded.
=> Enable address sanitizer in Github Action for ATfE.

.github/workflows/atfe_post_merge.yml, arm-software/embedded/scripts/test_post-merge.sh
- This workflow runs after a PR is merged into arm-toolchain or release/arm-software/**
- It builds and tests ATfE
=> Add post-merge workflow for ATfE

.github/workflows/atfe_address_sanitizer_build_and_test.yml
Update Github runner to large runner, for executing address sanitizer in Github Action for ATfE.
=> Update Github runner to large runner, for executing address sanitizer

CONTRIBUTING.md
Angle brackets without code block in markdown should be encoded as &lt; and &gt;. The text in between them was missing from the rendered HTML page and looked incomplete.
=> Fix formatting and clarify marking of downstream changes

arm-software/embedded/arm-runtimes/CMakeLists.txt
Follows from https://github.com/llvm/llvm-project/pull/144114 LLVM-libc doesn't provide all functions, but it is reasonable to expect the signature in the header file, consistent with picolibc. This allows the user to implement it later.
=> Enable all headers on LLVM-libc

libcxx/include/fstream, libcxx/src/ios.instantiations.cpp, libcxx/src/ostream.cpp, libcxx/test/std/input.output/file.streams/fstreams/filebuf.members/native_handle.pass.cpp, libcxx/test/std/input.output/file.streams/fstreams/filebuf.members/open_pointer.pass.cpp, libcxx/test/std/input.output/file.streams/fstreams/fstream.cons/pointer.pass.cpp, libcxx/test/std/input.output/file.streams/fstreams/fstream.members/native_handle.pass.cpp, libcxx/test/std/input.output/file.streams/fstreams/fstream.members/open_pointer.pass.cpp, libcxx/test/std/input.output/file.streams/fstreams/ifstream.members/native_handle.pass.cpp, libcxx/test/std/input.output/file.streams/fstreams/ifstream.members/offset_range.pass.cpp, libcxx/test/std/input.output/file.streams/fstreams/ofstream.cons/pointer.pass.cpp, libcxx/test/std/input.output/file.streams/fstreams/ofstream.members/native_handle.pass.cpp, libcxx/test/std/input.output/file.streams/fstreams/ofstream.members/open_pointer.pass.cpp, libcxx/test/std/input.output/file.streams/lit.local.cfg, libcxx/test/support/platform_support.h
Downstream issue: #375
This enables fstream for embedded systems where basic file operations are available via semihosting, but not additional filesystem operations like managing directories.
=> Enable fstream independently of filesystem

arm-software/embedded/arm-runtimes/CMakeLists.txt
After -O2 optimization was removed in https://github.com/arm/arm-toolchain/pull/349 it was reported that memory usage increased a lot https://github.com/arm/arm-toolchain/issues/352
The proposed solution is to use -Os which is based on -O2, but takes care of code size that is important in embedded applications.
=> Set newlib optimization level to -Os

arm-software/embedded/arm-runtimes/CMakeLists.txt, arm-software/embedded/arm-runtimes/test-support/modify-compiler-rt-xml.py
When building the compiler-rt project using its standalone mode, its
CMake files will load the data from the pre-existing LLVM build via
`find_package(LLVM)` to collect information about the build
configuration. Doing this has the side effect of also including all the
libraries used by the pre-existing LLVM build as CMake targets of the
compiler-rt sub-project.
As the compiler-rt variants are being cross-compiled as part of ATfE to
target embedded environments, loading the library targets pre-compiled
to target the host environment during the LLVM build can cause conflicts
in CMake. Such incompatibilities have started to trigger an error during
ATfE builds on recent versions of CMake - e.g. version 4 and above -,
where the shared libraries (such as libLTO) will be reject by CMake when
the …
=> [ATfE] Use the runtimes project to build compiler-rt

arm-software/embedded/llvmlibc-support/crt0/bootcode.cpp
To fix some of the nightly failing build errors (introduced by the patch https://github.com/arm/arm-toolchain/pull/394) which was caused by the ARMv4T variant, stub functions need to be introduced temporarily. 
Previously, only ARM architectures 'A', 'R' and 'M' were considered, therefore the `#if ... #endif` clause would miss any other variants. When tests are able to run, we can fill in the stub functions to fix any future failed tests, but up until the tests, this acts to suppress the build errors.
=> [ATfE] Fix bootcode not working for ARMv4T

.github/workflows/check_downstream_changes.yml, arm-software/ci/check_downstream_changes.py
In order to follow the project's downstream patch policy (see
CONTRIBUTING.md), modifications to the LLVM codebase (all files outside
the arm-software sub-directory, with a few exceptions) need to have a
issue opened in GitHub in order to track the changes, with the pull
request linking to that issue.
This patch implements a Python script and a GitHub workflow to run the
script whenever a pull request is opened or modified. The script takes a
pull request number, and uses the GitHub command-line interface to get
information about which files are changed, and whether the body text of
the pull request contains the required linkage. To determine which files
need tracking, the file changes are compared against the automerge
ignore list, which already contains the rules for which files are …
=> [Cherry-pick] Add automated check for downstream changes

arm-software/embedded/arm-multilib/json/variants/aarch64a.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_be.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_be_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_be_soft_nofp.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_be_soft_nofp_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_soft_nofp.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_soft_nofp_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_unaligned.json, arm-software/embedded/arm-multilib/json/variants/aarch64r.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_be.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_be_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_be_soft_nofp.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_be_soft_nofp_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_soft_nofp.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_soft_nofp_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_soft_nofp_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_soft_nofp_unaligned.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_unaligned.json
We have the need to support client code built with Position Independent Code (PIC) for AArch64.
Since PIC libraries are compatible with either PIC and non-PIC code, instead of duplicating all AArch64 libraries for PIC, we decided to transform the existing libraries into PIC.
=> [ATfE] Build AArch64 libraries with -fPIC

arm-software/embedded/scripts/test_atfe_sanitizer.sh
Update test script for sanitizers, to handle the failure in check-all tests. Now, script does not exit on the non-zero failure. Also, to indicate which command being executed, the commands are separated into individual lines and verbose is enabled.
=> Update test script for sanitizers, to handle the failure in check-all tests.

arm-software/embedded/arm-multilib/json/variants/armv8m.main_hard_fp_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv8m.main_hard_fp_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv8m.main_soft_nofp_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/armv8m.main_soft_nofp_unaligned.json
The variants for Armv8-M Main must be built heeding code size as they target the M-profile.
We change them to minsize instead of creating new variants because we anticipate that users interested in flat out performance will target Armv8.1-M Main, for which we'll still provide variants built with Release build type.
=> [ATfE] Build `armv8m.main` picolibc with minsize

SECURITY.md, arm-software/ci/.automerge_ignore
This extends the SECURITY.md inherited from the LLVM Project by adding details on how to report security issues for components not provided by LLVM Project.
SECURITY.md file was added to the automerge ignore list in a separate PR.
=> Extend SECURITY.md with Arm Toolchain details

arm-software/embedded/arm-multilib/multilib.yaml.in, arm-software/embedded/test/multilib/rwpi.test
ATfE doesn't currently provide any library variants built for RWPI. And if you link RWPI with non-RWPI code, nothing good will happen – they have incompatible ABIs. So we ought to give an error message rather than silently choose an incompatible library.
Using https://github.com/llvm/llvm-project/pull/149132 which allowed multilib selection to be aware of the relocation model at all, this commit does the simplest possible thing: adds a catch-all error message that will trigger on _any_ use of `-frwpi`, and report that there's no suitable library variant.
(Another possibility would have been to add `-fno-rwpi` to the validity criteria for each existing library, but that seemed less likely to give a good error message. It would allow RWPI variants to be present for some cases but not all, …
=> [ATfE] Fail with an error message when -frwpi is used.

.github/workflows/sync_from_upstream.yml
Include the upstream release branch in the "Sync from Upstream LLVM" workflow.
(Step 2 from our branching guide)
=> Include the upstream release branch in the "Sync from Upstream LLVM" workflow.

arm-software/embedded/patches/llvm-project/0008-Compiler-rt-FVP-and-QEMU-do-not-support-crash-signal.patch, arm-software/embedded/patches/llvm-project/0009-Clang-XFAIL-tests-with-frwpi-as-ATFE-don-t-have-an-a.patch
Three tests need to be marked as XFAIL due to the following reasons:
1. FVP AND QEMU are unable to handle crash related signals.
2. There is no compatible library available when the tests are run with -frwpi.
(cherry picked from commit 96378a4742ed7ebf9ed9c7d0e1f599cd4ab02b7b)
=> [ATFE] Mark tests XFAIL via downstream patching. (#430)

clang/include/clang/Driver/Multilib.h, clang/lib/Driver/Multilib.cpp, clang/lib/Driver/ToolChains/BareMetal.cpp, clang/test/Driver/baremetal-multilib-includedirs-error.yaml, clang/test/Driver/baremetal-multilib-includedirs.yaml
Downstream issue:#446.
This patch extends the Multilib yaml format to allow specifying an IncludeDirs for the header path/s per multilib variant. The goal is to enable fine-grained control over header search paths for each multilib variant. This feature is especially useful in setups where header paths deviate from the default bare-metal assumptions. For example, when headers are shared across target triples, it becomes necessary to organise them under target-triple-specific directories to ensure correct resolution.
This is already in upstream review https://github.com/llvm/llvm-project/pull/146651.
Since the review is pending, a downstream patch is made to enable IncludeDirs support in multilib.yaml
=> [Downstream change][Multilib] Extend the Multilib system to support an IncludeDirs field.

arm-software/embedded/arm-multilib/common-headers-generate.py
This patch introduces additional error checking and handle edge cases in common header generation script.
1. Adds a check to handle cases where the multilib folder is either empty or does not exist, avoiding unhandled exceptions.
2. Improves logic by allowing header optimisation to proceed for targets that have more than two variants, even if another target lacks sufficient variants for a comparison. These changes ensure the script can still performing valid optimisations where possible.
3. Copying multilib.yaml can be moved outside the loop, as it only needs to be done once after all target folders are generated.
=> [ATFE] Improve error handling and header optimisation in common header generation logic.

arm-software/embedded/arm-multilib/CMakeLists.txt
By default the toolchain enables all available library variants to be built, but a list of specific variants can instead be enabled through the `-DLLVM_TOOLCHAIN_LIBRARY_VARIANTS` option. Currently, if an invalid name is specified, the configuration will not notice and that variant will silently not be built. This patch instead causes the script to throw an error, so that it is clear that an expected variant is missing if the name is incorrect.
=> [ATfE] Throw an error if a requested variant name is not found

arm-software/embedded/patches/picolibc/0004-Revert-Delete-dummyhost.patch
This is not an approach that is going to be used in later releases, but it does give us time to work on a more complete solution.
=> Revert the upstream picolibc removal of dummyhost library.

arm-software/embedded/CMakeLists.txt
This is a release branch, so the -pre suffix is inappropriate.
=> [ATfE]: Remove "pre" suffix to release files.

arm-software/embedded/arm-multilib/json/variants/armv8m.main_hard_fp_exn_rtti_unaligned_size.json, arm-software/embedded/arm-multilib/json/variants/armv8m.main_hard_fp_unaligned_size.json, arm-software/embedded/arm-multilib/json/variants/armv8m.main_soft_nofp_exn_rtti_unaligned_size.json, arm-software/embedded/arm-multilib/json/variants/armv8m.main_soft_nofp_unaligned_size.json
The compiler-rt tests on Armv8-M Main are passing, so it's time we enable them.
=> [ATfE] Enable compiler-rt tests on Armv8-M Main variants

arm-software/embedded/arm-multilib/json/variants/armv4t_exn_rtti_size.json, arm-software/embedded/arm-multilib/json/variants/armv5te_exn_rtti_size.json
The tests are passing now, so we can enable them.
=> [ATfE] Enable picolibc, compiler-rt and libcxx texts for armv4t and armv5te exn_rtti

arm-software/shared/elf2bin/bin.cpp, arm-software/shared/elf2bin/test/test.py
(And also from --vhxcombined, which uses the same underlying code, but that didn't fit in a sensible-length subject line.)
Last week I found Arm Toolchain had generated an ELF image in which three segments had p_paddr in the bottom few Kb of the address space, but there was also a segment with zero p_filesz (but nonzero p_memsz), with p_paddr > 0x20000000. Running that through `elf2bin --physical --bincombined`, it didn't notice that the segment at a high address had length 0, so it padded the output file to half a Gb in size to reach the start address, and then didn't actually write anything there.
I worked around it at the time by selecting a subset of the segments to put in the --bincombined output file. But I think a better answer is to discard the zero-length segment completely when …
=> [elf2bin] Exclude zero-length segments from --bincombined.

arm-software/embedded/arm-multilib/json/variants/aarch64a.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_be.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_be_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_be_soft_nofp.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_be_soft_nofp_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_soft_nofp.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_soft_nofp_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64a_unaligned.json, arm-software/embedded/arm-multilib/json/variants/aarch64r.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_be.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_be_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_be_soft_nofp.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_be_soft_nofp_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_soft_nofp.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_soft_nofp_exn_rtti.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_soft_nofp_exn_rtti_unaligned.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_soft_nofp_unaligned.json, arm-software/embedded/arm-multilib/json/variants/aarch64r_unaligned.json
In the procedure call standard, `X18` is reserved for the platform. As a bare-metal toolchain we don't know what the platform will be so avoid using `X18` in case it is used by other code.
The clang's `-fsanitize=shadow-call-stack` is one such feature that relies on `X18` not being modified by the library.
=> [ATfE] Build AArch64 library variants with `-ffixed-x18`

arm-software/embedded/docs/newlib.md
The marker has to be on a separate line to show correctly.
=> NFC: Fix note markdown formatting

arm-software/embedded/llvmlibc-support/semihost/semihost.cpp
This is required for testing, where we need to return a code of 1. Previously, semihosting would always exit with status OK no matter the return code for AArch32.
Add minor fixes with C++ syntax.
=> [ATfE] Fix issue in semihosting with returning errors

.github/workflows/automerge.yml
This temporarily disables Automerge workflow runs for the 21.x release
branch. As the 21.x release approaches upstream, this is necessary to
ensure the commit used for the Arm Toolchain release is consistent
with the one used upstream.
While the Automerge is disabled for the branch, any incoming changes
from upstream will be reviewed and manually merged into the downstream
release/arm-software/21.x branch.
The workflow will be re-enabled for the branch once the release is done.
=> Temporarily disable automerge for 21.x release branch

arm-software/embedded/llvmlibc-samples/ldscripts/llvmlibc-raspi3b.ld, arm-software/embedded/llvmlibc-samples/src/baremetal-semihosting-aarch64-llvmlibc/Makefile, arm-software/embedded/llvmlibc-samples/src/baremetal-semihosting-aarch64-llvmlibc/hello.c, arm-software/embedded/llvmlibc-samples/src/baremetal-semihosting-aarch64-llvmlibc/make.bat, arm-software/embedded/llvmlibc-support/crt0/bootcode.cpp, arm-software/embedded/llvmlibc-support/llvmlibc.ld.in
This is based on the AArch64 sample from picolibc. This requires a minor hack. We need to place the _start at the beginning of the boot_flash section, and run QEMU from 0x0. This allows QEMU to turn off multithreading, and reach the _start symbol.
We use the section `.text.init.enter` for this. We do need extra space in `boot_flash`, because we also put the page table in this section.
=> [ATfE] Add AArch64 samples for LLVM-libc

arm-software/embedded/llvmlibc-support/crt0/bootcode.cpp, arm-software/embedded/llvmlibc-support/crt0/exceptions_7a.h, arm-software/embedded/llvmlibc-support/crt0/exceptions_8a.h, arm-software/embedded/llvmlibc-support/crt0/exceptions_a.h, arm-software/embedded/llvmlibc-support/crt0/exceptions_common.h, arm-software/embedded/llvmlibc-support/crt0/exceptions_m.h, arm-software/embedded/llvmlibc-support/crt0/memory_7a.h, arm-software/embedded/llvmlibc-support/crt0/memory_8a.h, arm-software/embedded/llvmlibc-support/crt0/memory_a.h, arm-software/embedded/llvmlibc-support/crt0/memory_common.h, arm-software/embedded/llvmlibc-support/crt0/system_registers_a.h, arm-software/embedded/llvmlibc-support/crt0/system_registers_common.h, arm-software/embedded/llvmlibc-support/crt0/system_registers_m.h, arm-software/embedded/llvmlibc-support/semihost/semihost.cpp, arm-software/embedded/llvmlibc-support/semihost/semihost.h
C casts have been changed to `reinterpret_cast` or `static_cast`. Defines have been changed to `inline constexpr`. GNU attributes have been changed to `[[c++11]]` style attributes.
No functional change. Everything still works.
=> [ATfE][NFC] Modernise llvmlibc-support to use C++ style code

.github/workflows/atfe_nightly_build_and_test.yml, arm-software/embedded/scripts/test_llvmlibc.sh
LLVM-libc tests can now be run for a lot of variants. This is experimental, however, there should be no reason why these tests won't run.
=> [ATfE] Enable LLVM-libc tests in nightly

arm-software/embedded/arm-multilib/multilib-generate.py
The function `get_extension_list()` in this script parses the output of `clang --target=[...] --print-supported-extensions` to make a list of architecture extension names. It's supposed to work for both AArch32 and AArch64, but in fact it was ignoring all AArch32 extensions, because clang gives differently formatted output for the two architectures, the parsing code was specific to the AArch64 version, and it silently ignored any unrecognised line instead of reporting an error.
I've replaced the previous parser with one that can handle both formats. Also, it reads the output more thoroughly, and objects to anything it doesn't completely understand. So if clang changes the format of this output in future, we'll have to fix this script, but we'll at least know that, and won't find out that …
=> [multilib-generate.py] Fix parsing of AArch32 extensions

arm-software/embedded/docs/llvmlibc.md
Also change the command to something that will compile, as well as remove the `errno` comment, which is no longer true as of #436
=> [ATfE] Add reference to llvmlibc.ld in the LLVM-libc docs

arm-software/embedded/scripts/build_llvmlibc_overlay.sh, arm-software/embedded/scripts/build_llvmlibc_toolchain.sh
Overlay builds are being killed at config time due to an unknown reason. Disabling parallel config is a workaround that gets us green builds for now. This will be reverted when the underlying cause is fixed.
=> [ATfE] Disable parallel multilib configuration steps

arm-software/embedded/scripts/test_llvmlibc.sh
`build` does not exist, use `build_llvmlibc_overlay`
=> [ATfE] Fix test_llvmlibc.sh

arm-software/embedded/arm-runtimes/CMakeLists.txt
The Python script for running QEMU has some additional logic for `virt` machines, which cannot be easily written in CMake. Therefore, just use that, hopefully that will fix a bug in CI. Also pass `-k 0` directly to the underlying CMake, which will allow all tests to run.
=> [ATfE] Fix LLVM-libc testing issue with CI

.github/workflows/atfe_nightly_build_and_test.yml, arm-software/embedded/arm-runtimes/CMakeLists.txt, arm-software/embedded/arm-runtimes/test-support/modify-compiler-rt-xml.py, arm-software/embedded/scripts/test.sh, arm-software/embedded/scripts/test_atfe_sanitizer.sh, arm-software/embedded/scripts/test_libcxx.sh, arm-software/embedded/scripts/test_post-merge.sh, arm-software/embedded/scripts/test_pre-merge.sh
Currently, some test suites are hard-coded to use a specific name/path to write xml results to. Others rely on this being set manually. Some of the CI scripts don't set it at all for certain test targets.
This patch aligns all the test suites to use the same name, controlled via the same mechanism. A user or CI system can set the `--xunit-xml-output` lit option via the `LIT_OPTS` environment variable to control the name of xml file, and therefore know the correct name to look for when storing the results.
A few minor corrections have also been made to the CI scripts for running tests:
* Since ninja defaults to building in parallel, so there is no reason to set the `-j` option.
* `check-all` was getting built twice in some scripts.
* Comments and lit options updated to reflect that …
=> [ATfE] Use a consistent name for xml results

arm-software/embedded/llvmlibc-support/crt0/exceptions_m.h, arm-software/embedded/llvmlibc-support/crt0/memory_common.h
The declaration is inside a C++ namespace, thus needs to be explicitly extern "C" to avoid name mangling. Further, all declarations of __start need to be updated to match.
=> [ATfE] Mark __stack declaration as extern "C"

arm-software/linux/docs/GettingStarted.md, arm-software/linux/docs/UsingArmPL.md
The extra line is added for some reason in PDF in case of all the items that span into more than one line.
=> [ATfL] Try to get rid of an extra line rendered in PDF

arm-software/embedded/arm-runtimes/CMakeLists.txt
The picolibc tests generally take longer to run using FVPs compared to using qemu, in addition to certain variants being specifically slower by the nature of what they enable.
=> [ATfE] Increase timeout for all picolibc tests using FVPs
