arm-software/linux/build.sh

The `build.sh` script has been developed independently without any awareness of the reality in which is being used in this repository.
The source directory is now the top level one, and the extra libraries may not always be available.

[ATfL] Make build.sh script more suitable to work with this codebase

---

arm-software/embedded/scripts/build_newlib_nano_overlay.sh

Add newlib-nano build script based on newlib one.

Add newlib-nano build script

---

arm-software/embedded/arm-multilib/json/multilib.json
arm-software/embedded/arm-multilib/json/variants/armebv7m_soft_fpv4_sp_d16.json
arm-software/embedded/arm-multilib/json/variants/armebv7m_soft_fpv4_sp_d16_exn_rtti.json
arm-software/embedded/arm-multilib/multilib.yaml.in
arm-software/embedded/test/multilib/armv7m.test

(cherry picked from https://github.com/arm/arm-toolchain/pull/50)

Add armebv7m_soft_fpv4_sp_d16 variants (#50)

---

arm-software/embedded/arm-multilib/json/multilib.json
arm-software/embedded/arm-multilib/json/variants/armebv7m_soft_nofp.json
arm-software/embedded/arm-multilib/json/variants/armebv7m_soft_nofp_exn_rtti.json
arm-software/embedded/test/multilib/armv7m.test

(cherry picked from https://github.com/arm/arm-toolchain/pull/51)

Add armebv7m_soft_nofp variants (#51)

---

arm-software/embedded/arm-multilib/json/multilib.json
arm-software/embedded/arm-multilib/json/variants/armebv7a_hard_vfpv3_d16.json
arm-software/embedded/arm-multilib/json/variants/armebv7a_hard_vfpv3_d16_exn_rtti.json
arm-software/embedded/arm-multilib/json/variants/armebv7a_soft_nofp.json
arm-software/embedded/arm-multilib/json/variants/armebv7a_soft_nofp_exn_rtti.json

(cherry picked from https://github.com/arm/arm-toolchain/pull/92)

Add armebv7a_soft_nofp and armebv7a_hard_vfpv3_d16 variants (#92)

---

arm-software/embedded/arm-multilib/json/multilib.json
arm-software/embedded/arm-multilib/json/variants/armebv7a_soft_vfpv3_d16.json
arm-software/embedded/arm-multilib/json/variants/armebv7a_soft_vfpv3_d16_exn_rtti.json
arm-software/embedded/arm-multilib/multilib.yaml.in
arm-software/embedded/test/multilib/armv7a.test

(cherry picked from https://github.com/arm/arm-toolchain/pull/98)

Add armebv7a_soft_vfpv3_d16 variants

---

arm-software/linux/README.md

[ATfL] Follow the trademarks guidance in our readme file

---

arm-software/ci/automerge.py

This updates the automerge script to detect unexpected errors when
running the `git merge` command for each of the commits being merged.
We cannot rely on the command's exist status for that, as it will return
a non-zero status in case a conflict is present, so we check that a
merge operation is actually in progress after `git merge` is executed.
This is done by checking for the presence of the `.git/MERGE_HEAD` file
in the repository dir.

[Automerge] Detect unexpected errors when running git merge

---

arm-software/linux/build.sh

[ATfL] Set ARM_TOOLCHAIN_ID for the build

---

arm-software/linux/build.sh
arm-software/linux/mkmoduledirs.sh.var

Fixes the initial lmod support and extends bash autocompletion to the arm?lang* commands.

[ATfL] Support bash autocompletion and lmod

---

arm-software/embedded/ATfE-SBOM-newlib-overlay.spdx.json
arm-software/embedded/scripts/SBOM_Files/generate_ATfE-SBOM-newlib-overlay.py

Update SBOM JSON file for ATfE newlib overlay; and Python script which generates this SBOM JSON file.

Update SBOM JSON file for ATfE newlib overlay; and Python script which generates this SBOM JSON file.

---

arm-software/embedded/arm-runtimes/test-support/run_fvp.py

Two cherry-picks to the release branch to prevent picolibc tests intermittently failing:
- Don't overwrite semihosting-features file in FVP tests (#207) (1858ecf293a0cdc49025ff46d13cb844ad731a4b)
- Don't delete temporary semihosting-features file (#214) (6f235b5a5045b1b5e7cae0e10900e1b9d725f5f3)
This fixes the issue where the `:semihosting-features` file can be removed by one process while another attempts to read it.

[ATfE] Cherry-pick PRs #207 and #214 to 20.x release branch

---

arm-software/embedded/README.md

Update Readme file for ATfE as per the supported host OS support.

Update Readme file for ATfE as per the supported host OS support.

---

arm-software/embedded/newlib-samples/src/baremetal-semihosting-newlib/make.bat
arm-software/embedded/newlib-samples/src/cpp-baremetal-semihosting-newlib/make.bat

This adapts the existing Makefile from the newlib samples to a make.bat so that the samples can be run on Windows.

Add make.bat files for the newlib samples

---

arm-software/embedded/CMakeLists.txt

Add CFI ignore file for ATfE.

---

arm-software/embedded/docs/building-from-source.md

Update the section for OSes for building from sources.

Update the section for OSes for building from sources.

---

llvm/lib/Analysis/IVDescriptors.cpp
llvm/test/Transforms/LoopVectorize/epilog-iv-select-cmp.ll
llvm/test/Transforms/LoopVectorize/iv-select-cmp-no-wrap.ll
llvm/test/Transforms/LoopVectorize/iv-select-cmp-trunc.ll
llvm/test/Transforms/LoopVectorize/iv-select-cmp.ll
llvm/test/Transforms/LoopVectorize/select-min-index.ll

[Downstream change][LV] Partially block upstream code causing 'Verification Error' on Grace

---

arm-software/linux/CHANGELOG.md
arm-software/linux/build.sh
arm-software/linux/build.sh-HOWTO.md

[ATfL] Add changelog

---

arm-software/linux/docs/Installation.md

[ATfL] Update URLs in the Installation.md file

---

CONTRIBUTING.md
arm-software/embedded/README.md
arm-software/linux/README.md

Softened the wording of when to raise issues in LLVM/picolibc vs arm-toolchain

[Downstream Change] Improved wording on issue reporting in the contribution guide

---

.github/workflows/atfe_nightly_build_and_test.yml

- The runners are hosted and maintained by Arm
- c7g.8xlarge
- Ubuntu 22.04

Add self hosted runners

---

.github/workflows/atfe_nightly_build_and_test.yml
arm-software/embedded/scripts/install_dependencies.ps1

- Update workflow matrix to add support for different operating systems and architectures in line with product requirements
- Add script to install dependencies for Windows
- Update workflow to support Windows

Build ATfE on Windows Server 2022

---

arm-software/embedded/README.md
arm-software/embedded/docs/atfe-dev-drop-builds.md
arm-software/embedded/docs/atfe-nightly-builds.md

- Create dedicated .md file
- Update README

Create documentation for ATfE Dev Drop builds

---

arm-software/embedded/scripts/test_atfe_sanitizer.sh

Update test script for sanitizers, reducing the list of covered tests to optimal coverage.

Update test script for sanitizers, reducing the list of covered tests to optimal coverage.

---

arm-software/embedded/README.md

We support v9-A code-generation. We map the v9-A family to the v8-A C-libraries.

Update README.md with Armv9-A support.

---

arm-software/embedded/scripts/test_post-merge.sh

- Test relevant targets in post-merge

[ATfE] Update post-merge workflow test targets

---

.github/workflows/atfe_pre_merge.yml

- Set env variables for ccache
- Update cache restore patch

[ATfE] Configure ccache in pre-merge

---

.github/workflows/atfe_pre_merge.yml

- Use the correct github workspace variable

[ATfE] Update ccache env variables

---

.github/workflows/automerge.yml

Adjust the "Automerge" Workflow to include the new downstream Branch
(This is step 4 of out Branching Guide)

Adjust the "Automerge" Workflow to include the new downstream Branch

---

arm-software/ci/check_downstream_changes.py

The current regular expression used to match the downstream issue line does not allow for the line to be indented with whitespace. This can be relaxed to prevent the check failing unnecessarily.
Additionally this adds a dryrun option to the script, to prevent the script making modifications during local testing.

Allow additional whitespace in downstream issue tagging

---

arm-software/embedded/docs/building-from-source.md

Update the the Building from source docs page by correcting obvious mismatches with current state and simplifying the structure a bit to make it easier to follow.

Update the Building from source page

---

arm-software/linux/docs/GettingStarted.md
arm-software/linux/docs/Installation.md
arm-software/linux/docs/PortingFromACfL.md
arm-software/linux/docs/UsingArmPL.md
arm-software/linux/docs/UsingBOLT.md
arm-software/linux/docs/index.md

Two changes introduced here:
- improved and simplified structure
- inconsistencies removed

[ATfL][docs] Introduce structural changes into documentation and fix inconsistent parts

---

arm-software/linux/docs/GettingStarted.md
arm-software/linux/docs/UsingArmPL.md

The extra line is added for some reason in PDF in case of all the items that span into more than one line.

[ATfL] Try to get rid of an extra line rendered in PDF

---

arm-software/linux/docs/OpenMPSupport.md
arm-software/linux/docs/PortingFromACfL.md

[ATfL] Reword parts causing glitches during PDF rendering
